production:
  adapter: postgresql
  host: ''
  database: tarot_api_production
  username: postgres
  password:
  encoding: unicode
  pool: 5

development:
  host: 'localhost'
  port: 5432
  adapter: postgresql
  database: tarot_api_dev
  username: postgres
  password: postgres

test:
  host: 'localhost'
  port: 5432
  adapter: postgresql
  database: tarot_api_test
  username: postgres
  password: postgres
